[package]
name = "KEEPITUP-Backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chatgpt = "0.1.0"
chatgpt_rs = "1.2.3"
dotenv = "0.15.0"
rocket = "=0.5.0-rc.3"
